name: Build & Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login bei ACR
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build und Push Docker-Image
        run: |
          az acr login --name presentationog3
          docker build -t presentationog3.azurecr.io/mein-app:latest .
          docker push presentationog3.azurecr.io/mein-app:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: presentationtest
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: |
            presentationog3.azurecr.io/mein-app:latest

      - name: Web-App neustarten
        run: |
          az webapp restart \
            --resource-group SKCLAR-PAILER \
            --name presentationtest
            
